paths:
  data_dir: "./data"
  reports_dir: "./reports"
  log_dir: "./logs"
  status_json: "./reports/last_status.json"
  snapshot_txt: "./reports/last_snapshot.txt"
  pid_file: "./scanner.pid"

market:
  horizons: [1, 10, 30, 60]
  pnl_thresh: 0.5
  winrate_min: 0.3

features:
  rsi_period: 14
  fast_sma: 9
  slow_sma: 21
  vol_spike_window: 60
  vol_mult: 2.0

report:
  interval_min: 20

strategy: pump
pump:
  entry: breakout
  z_win: 60
  vol_z_breakout: 3.0
  squeeze_win: 60
  squeeze_bb: 0.02
  near_upper_lookback: 60
  near_upper_eps: 0.003
  vol_ramp_win: 30
  vol_ramp_ratio: 1.5
  breakout_n_high: 30
  pre_score_min: 3
  pump_ret_1m: 0.02
